// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';


function thingToJs(param) {
  return {
          foo: param[/* foo */0],
          bar: param[/* bar */1]
        };
}

function thingFromJs(param) {
  return /* record */[
          /* foo */param.foo,
          /* bar */param.bar
        ];
}

var thing1 = /* record */[
  /* foo */"a",
  /* bar */1
];

console.log(thing1);

console.log(thingToJs(thing1));

exports.thingToJs   = thingToJs;
exports.thingFromJs = thingFromJs;
exports.thing1      = thing1;
/*  Not a pure module */
