// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

var Json        = require("bs-json/src/Json.js");
var Json_decode = require("bs-json/src/Json_decode.js");

function gameToJs(param) {
  return {
          name: param[/* name */0],
          players: param[/* players */1]
        };
}

function gameFromJs(param) {
  return /* record */[
          /* name */param.name,
          /* players */param.players
        ];
}

var json = " {\n  \"name\": \"Monopoly\",\n  \"players\": 6\n} ";

console.log(gameFromJs(Json.parseOrRaise(json)));

function decodeGame(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* players */Json_decode.field("players", Json_decode.$$int, json)
        ];
}

console.log(decodeGame(Json.parseOrRaise(json)));

var json2 = " [\n{\n  \"name\": \"Monopoly\",\n  \"players\": 6\n},\n{\n  \"name\": \"Catan\",\n  \"players\": 4\n}\n] ";

function decodeGames(json) {
  return Json_decode.list(decodeGame, json);
}

var json$1 = Json.parseOrRaise(json2);

console.log(Json_decode.list(decodeGame, json$1));

var json3 = " {\n  \"event\": \"Christmas\",\n  \"game\": {\n    \"name\": \"Monopoly\",\n    \"players\": 6\n  }\n } ";

exports.gameToJs    = gameToJs;
exports.gameFromJs  = gameFromJs;
exports.json        = json;
exports.decodeGame  = decodeGame;
exports.json2       = json2;
exports.decodeGames = decodeGames;
exports.json3       = json3;
/*  Not a pure module */
