// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var $$Array    = require("bs-platform/lib/js/array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var myListOfNumbers = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var listOfStrings = /* :: */[
  "a",
  /* :: */[
    "b",
    /* :: */[
      "c",
      /* [] */0
    ]
  ]
];

var anotherList = /* :: */[
  0,
  myListOfNumbers
];

console.log($$Array.of_list(listOfStrings));

console.log(listOfStrings);

console.log(Pervasives.string_of_int(List.length(myListOfNumbers)));

console.log(List.hd(listOfStrings));

console.log($$Array.of_list(List.tl(listOfStrings)));

console.log(List.nth(listOfStrings, 1));

console.log($$Array.of_list(List.rev(listOfStrings)));

var otherListOfStrings = /* :: */[
  "d",
  /* :: */[
    "e",
    /* :: */[
      "f",
      /* [] */0
    ]
  ]
];

console.log($$Array.of_list(List.append(listOfStrings, otherListOfStrings)));

console.log($$Array.of_list(Pervasives.$at(listOfStrings, otherListOfStrings)));

console.log($$Array.of_list(List.rev_append(listOfStrings, otherListOfStrings)));

var listOfLists_001 = /* :: */[
  otherListOfStrings,
  /* [] */0
];

var listOfLists = /* :: */[
  listOfStrings,
  listOfLists_001
];

console.log($$Array.of_list(List.concat(listOfLists)));

console.log($$Array.of_list(List.flatten(listOfLists)));

List.iter((function (element) {
        console.log(element);
        return /* () */0;
      }), listOfStrings);

List.iteri((function (index, string) {
        console.log(Pervasives.string_of_int(index) + (" " + string));
        return /* () */0;
      }), listOfStrings);

var listOfStringsWithExclamation = List.map((function (element) {
        return element + "!";
      }), listOfStrings);

console.log($$Array.of_list(listOfStringsWithExclamation));

var listOfStringsWithExclamation$1 = List.mapi((function (index, element) {
        return Pervasives.string_of_int(index) + (": " + element);
      }), listOfStrings);

console.log($$Array.of_list(listOfStringsWithExclamation$1));

exports.myListOfNumbers              = myListOfNumbers;
exports.listOfStrings                = listOfStrings;
exports.anotherList                  = anotherList;
exports.otherListOfStrings           = otherListOfStrings;
exports.listOfLists                  = listOfLists;
exports.listOfStringsWithExclamation = listOfStringsWithExclamation$1;
/*  Not a pure module */
