// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var $$Array    = require("bs-platform/lib/js/array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var myListOfNumbers = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var myListOfStrings = /* :: */[
  "a",
  /* :: */[
    "b",
    /* :: */[
      "c",
      /* [] */0
    ]
  ]
];

var anotherList = /* :: */[
  0,
  myListOfNumbers
];

console.log($$Array.of_list(myListOfStrings));

console.log(myListOfStrings);

console.log(Pervasives.string_of_int(List.length(myListOfNumbers)));

console.log(List.hd(myListOfStrings));

console.log($$Array.of_list(List.tl(myListOfStrings)));

console.log(List.nth(myListOfStrings, 1));

console.log($$Array.of_list(List.rev(myListOfStrings)));

var myOtherListOfStrings = /* :: */[
  "d",
  /* :: */[
    "e",
    /* :: */[
      "f",
      /* [] */0
    ]
  ]
];

console.log($$Array.of_list(List.append(myListOfStrings, myOtherListOfStrings)));

console.log($$Array.of_list(Pervasives.$at(myListOfStrings, myOtherListOfStrings)));

console.log($$Array.of_list(List.rev_append(myListOfStrings, myOtherListOfStrings)));

var listOfLists_001 = /* :: */[
  myOtherListOfStrings,
  /* [] */0
];

var listOfLists = /* :: */[
  myListOfStrings,
  listOfLists_001
];

console.log($$Array.of_list(List.concat(listOfLists)));

console.log($$Array.of_list(List.flatten(listOfLists)));

exports.myListOfNumbers      = myListOfNumbers;
exports.myListOfStrings      = myListOfStrings;
exports.anotherList          = anotherList;
exports.myOtherListOfStrings = myOtherListOfStrings;
exports.listOfLists          = listOfLists;
/*  Not a pure module */
