// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

var Module1$ReasonmlExamples = require("./Module1.bs.js");
var Module2$ReasonmlExamples = require("./subdir/Module2.bs.js");

console.log(Module1$ReasonmlExamples.authorName);

console.log(Module1$ReasonmlExamples.authorName);

console.log(Module2$ReasonmlExamples.authorName);

/*  Not a pure module */
