// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

console.log(Pervasives.string_of_bool(/* true */1));

console.log(Pervasives.string_of_bool(/* true */1));

console.log(Pervasives.string_of_bool(/* false */0));

console.log(Pervasives.string_of_bool(/* false */0));

console.log(Pervasives.string_of_bool(/* true */1));

console.log(Pervasives.string_of_bool(/* true */1));

console.log(Pervasives.string_of_bool(/* false */0));

console.log(Pervasives.string_of_bool(/* false */0));

function $$$(l0, l1) {
  return Caml_int32.imul(Caml_int32.imul(Caml_int32.imul(Caml_int32.imul(Caml_int32.imul(l0, l0), l0), l1), l1), l1);
}

console.log($$$(2, 3));

exports.$$$ = $$$;
/*  Not a pure module */
