// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

var Block      = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var message = "Loading";

console.log(message);

var info = /* Order */Block.__(1, [
    "Josh",
    26
  ]);

var greeting;

greeting = typeof info === "number" ? "How can I help you?" : (
    info.tag ? "You rordered " + (Pervasives.string_of_int(26) + " of Josh") : "Hello Josh!"
  );

console.log(greeting);

var dataLoadingStatus = /* Loading */0;

exports.dataLoadingStatus = dataLoadingStatus;
exports.message           = message;
exports.info              = info;
exports.greeting          = greeting;
/*  Not a pure module */
