// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var message = "Loading";

console.log(message);

var dataLoadingStatus = /* Loading */0;

exports.dataLoadingStatus = dataLoadingStatus;
exports.message           = message;
/*  Not a pure module */
